# Generated by Django 5.0.1 on 2024-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_praduct_praduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praduct',
            name='praduct_image',
            field=models.ImageField(blank=True, default='/image/no-image.png', null=True, upload_to='image/'),
        ),
    ]
