# Generated by Django 5.0.1 on 2024-01-14 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='OrderProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('delivered', models.BooleanField(default=False)),
                ('basket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Basket', to='user.basket')),
            ],
        ),
    ]
