# Generated by Django 5.0.1 on 2024-01-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_costomer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='image',
            field=models.ImageField(blank=True, default='/image/default.jpg', null=True, upload_to='image/'),
        ),
    ]
